print("Enter Integer:")
num1 = int(input())
print(f"You entered: {num1}")
print(f'And {num1} cubed is {num1 ** 3} !!')
print("Enter another integer:")
num2 = int(input())
print(f'{num1} + {num2} is {num1 + num2}')
print(f'{num1} * {num2} is {num1 * num2}')